### ISSUE TITLE
Assignment2b

### ISSUE THREAD

**Issue by AndreyIsakov01** [st129351/HomeAssignments#5]
В processing.cpp в условиях есть повторяющиеся куски кода, которые можно вынести за пределы условия или вынести в отдельную функцию

**Comment by st129351** [comment]
хорошо, выполнил

**Comment by lichkovahadaniil** [comment]
> В processing.cpp в условиях есть повторяющиеся куски кода, которые можно вынести за пределы условия или вынести в отдельную функцию

Здравствуйте, сделал
