### ISSUE TITLE
Assignment3

### ISSUE THREAD

**Issue by vkats-spbu** [st129351/HomeAssignments#6]
1. Не включайте в Ваши iostream и вообще любые другие библиотеки, которые не нужны непосредственно там - это лучше делать в файлах исходного кода
2. Тесты, очевидно, не запускаются. Ваша цель на тестирование выдает:
<pre><font color="#26A269"><b>victor@victor-VirtualBox</b></font>:<font color="#12488B"><b>~/accesment/st129351/HomeAssignments/Assignment3</b></font>$ ./tests
GAME ON!
</pre>
где отчет по тестам?

**Comment by lichkovahadaniil** [comment]
> 1. Не включайте в Ваши iostream и вообще любые другие библиотеки, которые не нужны непосредственно там - это лучше делать в файлах исходного кода
> 
> 2. Тесты, очевидно, не запускаются. Ваша цель на тестирование выдает:
> 
> <pre><font color="#26A269"><b>victor@victor-VirtualBox</b></font>:<font color="#12488B"><b>~/accesment/st129351/HomeAssignments/Assignment3</b></font>$ ./tests
> 
> GAME ON!
> 
> </pre>
> 
> где отчет по тестам?

Здравствуйте! Все поправил!
